dist: trusty
language: bash
before_install:
  - ./travis/prepare.sh
  - ./travis/run_checks.sh
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    rooms:
      - devops-team-otus:Pcdq7tJYXmLzNIv2nma8LJ4M#georgy_vashchenko
