dist: trusty
language: bash
before_install:
  - ./travis/prepare.sh
  - ./travis/run_checks.sh
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    rooms:
      - secure: Qemjio1HhEbzFvmJ/0bvTZjKKeQkvyssV0BnYbs1+kRpADZliaAcA/xVzLI4h/BrtP6YNYnbzGkwVCyxs6nDZ1myo7pRBVbSZXpHwjlVNJNwRUNO5yPOj9+s7UjlNAO2Rl400BuleFBlJT5kysKDs6xocaB4Ei8ox6P+g153VzvNoOatJpLJWnhbMXT7wzJMymvnVn/bHFvt9rGq+t4lIUQ/4F1E74VHUw1I4l8F82wWXNDYxg5sEbztzoaYMiUwY5ZwUMxwoj3JTSLdfaHMicNepnouwJZx6j2W/s07wqnvfTfVTbK47mucM25YZk475Y5sezq7cE38gE/qqXQNcUFO68iNuATwxknH28XC21GuhTesnkPPl4GeQOf1I+WjV3ZZi6VUp3onjkGEnexCW8ww68aFSO15CIQclCW2IrimhGxMp5RADtiSW7wgX2IIrb2+79B+WJsJQNZgX9rB0KF07r1VjLbjL/jPGqjD3IBPJeDZIN+ZuZ3PbCfEg0XJ8iK2ngDOZcitIcGCP6RnsdT8Ry5aWGf7V8DIps+oPZbxtVILgU0X0s3aREmU0B5/LDGIjW7yaOAqT0CKvhRqGBIif+jejXiZbFA0R1PGN5NhF0ZhcQ+fT0FWf9Ag8fMcctpdakgJb83IJbAEqRJcygdUEnHZPgFq2hnmYu2iWoY=
