---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key: url=https://www.mongodb.org/static/pgp/server-3.2.asc
      # Предложенный в gist'е ( https://gist.github.com/Nklya/bb2ca080692f75ef1cb2dd24a9926fa8 )
      # вариант добавляет ключ, не проходящий аутентикацию, что приводит к ошибке:
      #     install 'mongodb-org'' failed: E: There were unauthenticated packages and -y was used without --allow-unauthenticated

    - name: Add APT repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongodb package
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Enable mongod service
      systemd:
        name: mongod
        enabled: yes
